using UnityEngine;
using UnityEditor;
using UnityEngine.Rendering.Universal;

public class ConvertDecalsToMeshes : EditorWindow
{
    [MenuItem("Tools/SUMO/Convert Decal Projectors to Meshes")]
    public static void ConvertDecals()
    {
        // Find all Decal Projector components in the active scene
        DecalProjector[] decalProjectors = Object.FindObjectsByType<DecalProjector>(FindObjectsSortMode.None);
        
        if (decalProjectors.Length == 0)
        {
            Debug.LogWarning("No URP Decal Projectors found in the scene.");
            return;
        }

        GameObject meshParent = new GameObject("SUMO_RoadMarkings_Meshes");
        int convertedCount = 0;

        foreach (DecalProjector decal in decalProjectors)
        {
            // Create a simple Quad mesh GameObject at the decal's position
            GameObject quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
            quad.name = decal.gameObject.name + "_Mesh";
            quad.transform.SetParent(meshParent.transform);

            // Align position (raise Y slightly by 2mm to avoid Z-fighting)
            Vector3 pos = decal.transform.position;
            pos.y += 0.002f;
            quad.transform.position = pos;

            // Align rotation (Quads lie flat on the ground rotated 90 deg on X)
            quad.transform.rotation = decal.transform.rotation * Quaternion.Euler(90, 0, 0);

            // Scale the Quad based on the Decal Projector's size (X and Y parameters)
            Vector3 decalSize = decal.size;
            quad.transform.localScale = new Vector3(decalSize.x, decalSize.y, 1f);

            // Disable collider generated by Primitive
            DestroyImmediate(quad.GetComponent<MeshCollider>());

            // Hide or disable the original Decal Projector
            decal.gameObject.SetActive(false);

            convertedCount++;
        }

        Undo.RegisterCreatedObjectUndo(meshParent, "Convert Decals to Meshes");
        Debug.Log($"Successfully converted {convertedCount} URP Decal Projectors to Flat Quad Meshes!");
    }
}